# Generated by Django 5.2.10 on 2026-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
