# Generated by Django 5.2.10 on 2026-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracurricular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/photos/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
