# Generated by Django 5.2.10 on 2026-02-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_resume_location_resume_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
    ]
